@baseUrl=http://localhost:3000/api

POST {{baseUrl}}/auth/signup
Content-Type: application/json

{
    "email": "jude@gmail.com",
    "username": "uname2",
    "password": "Password1"
}

###

POST {{baseUrl}}/auth/signin
Content-Type: application/json

{
    "username": "uname1",
    "password": "Password1"
}

GET {{baseUrl}}/auth/refresh
Content-Type: application/json

###

DELETE {{baseUrl}}/auth/signout
Content-Type: application/json
Cookie: refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqd3RJZCI6IjVhNGZkZjgyLWQzNGUtNGY4Zi1hNjM4LTRiYjhkYjlkNGM2ZiIsImlkIjoiZWNmNGE2MmMtN2Q5Yi00NDM4LWE5YmEtYmZjMTU2NDBhZjQwIiwidXNlcm5hbWUiOiJ1bmFtZTEiLCJlbWFpbCI6ImVkQGdtYWlsLmNvbSIsImlhdCI6MTY4NzU0MTYzMCwiZXhwIjoxNjkwMTMzNjMwfQ.uvB5kJWgvWYOsEzYzldUGJgtYTK_Yyytnrbe2b9WeC4; Max-Age=2592000; Path=/; Expires=Sun, 23 Jul 2023 17:33:50 GMT; HttpOnly

###

DELETE {{baseUrl}}/auth/signout_all
Content-Type: application/json
Cookie: refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqd3RJZCI6IjVhNGZkZjgyLWQzNGUtNGY4Zi1hNjM4LTRiYjhkYjlkNGM2ZiIsImlkIjoiZWNmNGE2MmMtN2Q5Yi00NDM4LWE5YmEtYmZjMTU2NDBhZjQwIiwidXNlcm5hbWUiOiJ1bmFtZTEiLCJlbWFpbCI6ImVkQGdtYWlsLmNvbSIsImlhdCI6MTY4NzU0MTYzMCwiZXhwIjoxNjkwMTMzNjMwfQ.uvB5kJWgvWYOsEzYzldUGJgtYTK_Yyytnrbe2b9WeC4; Max-Age=2592000; Path=/; Expires=Sun, 23 Jul 2023 17:33:50 GMT; HttpOnly

###
