@baseUrl=http://localhost:3000/api

POST {{baseUrl}}/auth/signup
Content-Type: application/json

{
    "email": "lana@gmail.com",
    "username": "uname4",
    "password": "Password1"
}

###

POST {{baseUrl}}/auth/signin
Content-Type: application/json

{
    "username": "uname4",
    "password": "Password1"
}

GET {{baseUrl}}/auth/refresh
Content-Type: application/json

###

DELETE {{baseUrl}}/auth/signout
Content-Type: application/json
Cookie: refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqd3RJZCI6IjlkOWE4YzAyLWMwZTItNDViMC05Y2RlLWJhMzA3OTU3ZGFhNCIsImlkIjoiZWExMWE0NWItOTQyNy00MGNlLWFkYmEtZDQyOWExZmFkMzIyIiwidXNlcm5hbWUiOiJ1bmFtZTQiLCJlbWFpbCI6ImxhbmFAZ21haWwuY29tIiwiaWF0IjoxNjg3NjQ1MjgyLCJleHAiOjE2OTAyMzcyODJ9.XBLgKQocP90YHHVL2ic7c4y5xumUsOtWt9zAOk-S84A; Max-Age=2592000; Path=/; Expires=Mon, 24 Jul 2023 22:21:22 GMT; HttpOnly

###

DELETE {{baseUrl}}/auth/signout_all
Content-Type: application/json

###
